AllCops:
  TargetRubyVersion: 2.3

Lint/UnneededDisable:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false
